# Einführung in Pandas DataFrames

![Pandas](Pandas.png)

[Pandas](https://pandas.pydata.org/) ist eine leistungsstarke und vielseitige Bibliothek für Python, die primär für die Datenmanipulation und -analyse entwickelt wurde.

>Pandas ist die beliebteste Softwarebibliothek für Datenmanipulation und Datenanalyse für die Programmiersprache Python. ([www.nvidia.com](https://www.nvidia.com/en-us/glossary/pandas-python/))

Hier ist eine (unvollständige) Liste einiger wichtiger Funktionen von Pandas:

1. **Datenstrukturen**
- *Serie* : Eindimensionales, beschriftetes Array, das Daten beliebigen Typs aufnehmen kann.
- *DataFrame* : Zweidimensionale, größenveränderliche, potenziell heterogene tabellarische Datenstruktur mit beschrifteten Achsen (Zeilen und Spalten).

2. **Datenmanipulation**
- *Datenauswahl und -indizierung* : Zugriff auf Daten über Labels, Indizes oder Boolesche Masken (`.loc`, `.iloc`, `.at`, `.iat`).
- *Filtern* : Daten anhand von Bedingungen oder Abfragen filtern.
- *Sortierung* : Daten nach Bezeichnungen oder Werten sortieren.
- *Umgang mit fehlenden Daten* : Fehlende Werte identifizieren, ergänzen oder entfernen `isnull`, `dropna`, `fillna`).

3. **Datenbereinigung**
- *Duplikate entfernen* : Doppelte Zeilen oder Spalten entfernen.
- *Werte ersetzen* : Bestimmte Werte im DataFrame ersetzen.
- *String-Operationen* : ührt Operationen an String-Daten durch, wie z. B. Aufteilen, Ersetzen und Mustervergleich ( `str.split `,  `str.replace `).

4. **Aggregation und Gruppierung**
- *Gruppieren nach* : Daten anhand von Kriterien in Gruppen aufteilen und Aggregatfunktionen wie Summe, Mittelwert oder benutzerdefinierte Operationen durchführen.
- *Pivot-Tabellen* : Erstellen Sie eine Pivot-Tabelle, um Daten zusammenzufassen.

5. **Zusammenführung und Beitritt**
- *Verkettung* : Mehrere DataFrames entlang einer bestimmten Achse kombinieren.
- *Zusammenführen* : Zusammenführen von DataFrames ähnlich wie SQL-Joins (`merge`, `join`).

6. **Zeitreihen**
- *Datums-/Zeitkonvertierung* : Konvertiert Datums- und Zeitdaten in ein Datums-/Zeitobjekt.
- *Resampling* : Daten über einen bestimmten Zeitraum aggregieren.
- *Zeitbasierte Indizierung* : Mit der Datumsindizierung können Sie einfach auf Zeitreihendaten zugreifen und diese bearbeiten.

7. **Statistische und mathematische Operationen**
- *Deskriptive Statistik* : Berechnet zusammenfassende Statistiken für die Spalten des DataFrames.
- *Korrelation/Kovarianz* : Berechnen Sie die paarweise Korrelation oder Kovarianz zwischen den Spalten.
- *Kumulative Operationen* : Führe kumulative Operationen an Daten durch.

Das Herzstück von Pandas ist der DataFrame, eine zweidimensionale, beschriftete Datenstruktur mit Spalten potenziell unterschiedlicher Datentypen, ähnlich einer Tabelle in einer relationalen Datenbank oder einer Excel-Tabelle. Das Verständnis von DataFrames ist für jeden, der Datenanalysen in Python durchführen möchte, unerlässlich.

# Was ist ein DataFrame?
---
Ein DataFrame ist eine tabellenartige Struktur in Pandas, die aus Zeilen und Spalten besteht. Jede Spalte kann unterschiedliche Datentypen (z. B. Ganzzahlen, Gleitkommazahlen, Zeichenketten) enthalten. Man kann sich einen DataFrame als Sammlung von Series-Objekten vorstellen, wobei jede Series einer einzelnen Datenspalte entspricht. DataFrames bieten eine hocheffiziente Möglichkeit, große Datensätze im Arbeitsspeicher zu speichern und zu bearbeiten

# Erstellen eines DataFrames
---
Es gibt mehrere Möglichkeiten, einen DataFrame in Pandas zu erstellen, aber einige der gebräuchlichsten Methoden sind:
1. Aus einem Wörterbuch
2. Aus einer Liste von Listen
3. Aus einer CSV-Datei

Im Folgenden betrachten wir die ersten beiden Ansätze.

## Erstellen eines DataFrames aus einem Wörterbuch

Der folgende Code erstellt einen DataFrame mit drei Spalten: „Name“, „Alter“ und „Stadt“ sowie drei Zeilen, die den im Wörterbuch angegebenen Daten entsprechen. Um Pandas verwenden zu können, muss es zunächst importiert werden. Dies geschieht mit dem Befehl `import pandas as pd` import, wobei der Alias `pd` für Pandas verwendet wird.

In [11]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}

df = pd.DataFrame(data)

df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

## Erstellen eines DataFrames aus einer Liste von Listen

Hier erstellen wir den DataFrame aus einer Liste von Listen, wobei jede innere Liste die Werte für eine Zeile darstellt. Beachten Sie, dass wir die Spaltennamen beim Erstellen des DataFrames explizit angeben.

In [10]:
data = [
    ['Alice', 25, 'New York'],
    ['Bob', 30, 'Los Angeles'],
    ['Charlie', 35, 'Chicago']
]

df = pd.DataFrame(data, columns=['Name', 'Age', 'City'])

df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

# Zugriff auf Daten in einem DataFrame
---
Sobald Sie ein DataFrame haben, können Sie auf verschiedene Weise auf dessen Daten zugreifen:

- Nach Spaltennamen:

In [14]:
df['Name']

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: str

- Nach Zeilenindex:

In [16]:
df.iloc[0]

Name       Alice
Age           25
City    New York
Name: 0, dtype: object

- Beide verwenden:

In [17]:
df.loc[0, 'Name']

'Alice'

# Abschluss
---
Pandas DataFrames sind ein grundlegendes Werkzeug für die Datenanalyse in Python. Sie bieten eine leistungsstarke Möglichkeit, Daten effizient zu organisieren, zu bearbeiten und zu analysieren. Ob Sie mit kleinen Datensätzen oder großen Datenmengen arbeiten – wer DataFrames beherrscht, kann eine Vielzahl von datenbezogenen Aufgaben mühelos bewältigen.

In dieser Einführung haben wir die Grundlagen von DataFrames behandelt: Was ist ein DataFrame? Wie erstellt man einen? Und wie greift man auf Spalten, Zeilen und einzelne Zellen in einem DataFrame zu? Wenn Sie Pandas weiter erkunden, werden Sie viele weitere Funktionen und Möglichkeiten entdecken, die DataFrames zu einem unverzichtbaren Bestandteil der Python-Programmierung machen. Die folgende Tabelle enthält einige Ressourcen zu Pandas.

---

| Ressource | Beschreibung |
|-----------|--------------|
| https://pandas.pydata.org/docs/ | Offizielle Dokumentation für Pandas. |
| https://wesmckinney.com/book/ | Ausführlicher Leitfaden von Wes McKinney, dem Schöpfer von Pandas. | 
| https://realpython.com/pandas-dataframe/ | Anleitungen zur Verwendung von Pandas für die Datenanalyse. | 
| [Kaggle Pandas](https://www.kaggle.com/learn/pandas) | Kostenloser Einführungskurs zu Pandas von Kaggle. | 
| [DataCamp Pandas-Tutorial](https://www.datacamp.com/tutorial/pandas) | Ausführliche Tutorials und Übungen zu Pandas. |